### ISSUE TITLE
Unbookable dates

### ISSUE THREAD

**Issue by mattmb** [ministryofjustice/prison-visits#208]
There seems to be a bug regarding unbookable dates:
http://sentry.prod-prisonvisits.dsd.io/default/default/group/2308/

```
NoMethodError
undefined method `[]' for nil:NilClass
/lib/schedule.rb:7:in `initialize'
/app/controllers/deferred/slots_controller.rb:8:in `new'
/app/controllers/deferred/slots_controller.rb:8:in `edit'
```

**Comment by mattmb** [comment]
So after investigation:
https://github.com/ministryofjustice/prison-visits/blob/master/app/controllers/deferred/slots_controller.rb#L9
references `visit.prisoner.prison_name` and if this is nil we get this exception.

One way the user can cause this to happen:
* Start a new session, fill in the service.
* On the review page click edit against the prisoner details.
* Blank the prison name, press continue.
* You will get an error message. However the prison name is cleared from the session.
* Use back/forward buttons to navigate to the slot picker.

**Comment by matharden** [comment]
Do you agree this issue is now resolved? I've raised a new issue for the user side of this.

**Comment by mattmb** [comment]
Yep happy to track it in a new issue now that we know the root cause :smile:
