### ISSUE TITLE
Upgrade healthcheck.json to use same format as other services

### ISSUE THREAD

**Issue by SteveMarshall** [ministryofjustice/prison-visits#225]
Other services in MOJ use this format:

```json
{
  "database": {
    "description": "Postgres database",
    "ok": true
  },
  "smtp": {
    "description": "SendGrid",
    "ok": true
  },
  "api": {
    "description": "DWP API",
    "ok": false
  },
  "ok": false
}
```

This provides a slightly more useful, descriptive set of information than our current format, so we should consider moving to it at some point soon.

**Comment by threedaymonk** [comment]
Should we roll this into #258, as we're changing `healthcheck.json` anyway?

**Comment by SteveMarshall** [comment]
Yeah, that'd be good, I think.
